In [2]:
# importing libraries
import pandas as pd
import numpy as np

# TASK 1
dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [ ]:
salesData = pd.read_csv('dataset.csv')

totalGlobalSales = salesData.sum(axis=0, numeric_only=True)['Global_Sales']

print(f"Total Global Sales: ${totalGlobalSales}")

averageNA = salesData.mean(axis=0, numeric_only=True)['NA_Sales']
averageEU = salesData.mean(axis=0, numeric_only=True)['EU_Sales']
averageJP = salesData.mean(axis=0, numeric_only=True)['JP_Sales']
averageOther = salesData.mean(axis=0, numeric_only=True)['Other_Sales']

print(f"Average Sales in North America: ${averageNA}")
print(f"Average Sales in Europe: ${averageEU}")
print(f"Average Sales in Japan: ${averageJP}")
print(f"Average Sales in Other Regions: ${averageOther}")

top5Games = salesData.sort_values(by='Global_Sales', ascending=False).head(5)

print("Top 5 Games by Global Sales:")
display(top5Games)

groupedNA = salesData.groupby('Genre').sum()['NA_Sales']
groupedEU = salesData.groupby('Genre').sum()['EU_Sales']
groupedJP = salesData.groupby('Genre').sum()['JP_Sales']
groupedOther = salesData.groupby('Genre').sum()['Other_Sales']

print(f"Sales by Genre in North America:")
display(groupedNA)
print(f"Sales by Genre in Europe:")
display(groupedEU)
print(f"Sales by Genre in Japan:")
display(groupedJP)
print(f"Sales by Genre in Other Regions:")
display(groupedOther)
print(f"Most popular Genre in North America: {groupedNA.head(1)}")

display(salesData.tail(10))

top3Platforms = salesData.groupby('Platform').sum()['Global_Sales'].sort_values(ascending=False).head(3)

display(top3Platforms)

totalSum = salesData['Global_Sales'].sum()
genres = salesData.groupby('Genre')['Global_Sales'].sum() / totalSum * 100

print(f"Average Sales per Genre: {genres.sort_values(ascending=False)}")

print("Correlation (NA & EU): ", salesData['NA_Sales'].corr(salesData['EU_Sales']))


Total Global Sales: $8920.44
Average Sales in North America: $0.26466742981082064
Average Sales in Europe: $0.14665200626581515
Average Sales in Japan: $0.077781660441017
Average Sales in Other Regions: $0.0480630196409206
Top 5 Games by Global Sales:


Rank                      Name Platform    Year         Genre Publisher  \
0     1                Wii Sports      Wii  2006.0        Sports  Nintendo   
1     2         Super Mario Bros.      NES  1985.0      Platform  Nintendo   
2     3            Mario Kart Wii      Wii  2008.0        Racing  Nintendo   
3     4         Wii Sports Resort      Wii  2009.0        Sports  Nintendo   
4     5  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo   

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
0     41.49     29.02      3.77         8.46         82.74  
1     29.08      3.58      6.81         0.77         40.24  
2     15.85     12.88      3.79         3.31         35.82  
3     15.75     11.01      3.28         2.96         33.00  
4     11.27      8.89     10.22         1.00         31.37

Sales by Genre in North America:


Genre
Action          877.83
Adventure       105.80
Fighting        223.59
Misc            410.24
Platform        447.05
Puzzle          123.78
Racing          359.42
Role-Playing    327.28
Shooter         582.60
Simulation      183.31
Sports          683.35
Strategy         68.70
Name: NA_Sales, dtype: float64

Sales by Genre in Europe:


Genre
Action          525.00
Adventure        64.13
Fighting        101.32
Misc            215.98
Platform        201.63
Puzzle           50.78
Racing          238.39
Role-Playing    188.06
Shooter         313.27
Simulation      113.38
Sports          376.85
Strategy         45.34
Name: EU_Sales, dtype: float64

Sales by Genre in Japan:


Genre
Action          159.95
Adventure        52.07
Fighting         87.35
Misc            107.76
Platform        130.77
Puzzle           57.31
Racing           56.69
Role-Playing    352.31
Shooter          38.28
Simulation       63.70
Sports          135.37
Strategy         49.46
Name: JP_Sales, dtype: float64

Sales by Genre in Other Regions:


Genre
Action          187.38
Adventure        16.81
Fighting         36.68
Misc             75.32
Platform         51.59
Puzzle           12.55
Racing           77.27
Role-Playing     59.61
Shooter         102.69
Simulation       31.52
Sports          134.97
Strategy         11.36
Name: Other_Sales, dtype: float64

Most popular Genre in North America: Genre
Action    877.83
Name: NA_Sales, dtype: float64


Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64

Average Sales per Genre: Genre
Action          19.631094
Sports          14.920004
Shooter         11.629135
Role-Playing    10.396012
Platform         9.319832
Misc             9.079821
Racing           8.206322
Fighting         5.032375
Simulation       4.396644
Puzzle           2.745941
Adventure        2.679688
Strategy         1.963132
Name: Global_Sales, dtype: float64
0.7677267483702641


## Task 2 English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [8]:
translation = {
    'hello': 'hola',
    'car': 'auto',
    'dog': 'perro',
    'name': 'nombre'
}

while True:

    word = input("Enter word (Type 'q' to exit): ")

    if word.lower() == 'q':
        break

    if word.lower() in translation:
        print(f"{word.lower()} in Spanish is {translation[word.lower()]}")
    else:
        print(f"{word.lower()} not found in Dictionary")

hola
perro
Word not found
hola
Word not found
Word not found



## Task 3 Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [48]:
def classifyEmails(emails):
    important = ["urgent", "required", "deadline", "important"]
    promotions = ["discount", "deal", "sale"]
    spam = ["spam", "free"]
    categorizedEmails = {
        "important": [],
        "promotions": [],
        "spam": []
    }

    for email in emails:
        email = email.lower()
        if any(word in email for word in important):
            categorizedEmails['important'].append(email)
        elif any(word in email for word in promotions):
            categorizedEmails['promotions'].append(email)
        elif any(word in email for word in spam):
            categorizedEmails['spam'].append(email)
        else:
            print(f"{email} not categorized!")

    return categorizedEmails

emails = [
    "Urgent: Please respond to this email!",
    "Discount on shoes",
    "Get free Netflix",
    "Please completed this task by the deadline",
    "New Sale on clothes"
]

display(classifyEmails(emails))

{'important': ['urgent: please respond to this email!',
  'please completed this task by the deadline'],
 'promotions': ['discount on shoes', 'new sale on clothes'],
 'spam': ['get free netflix']}

## Task 4 Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.

In [56]:
cart = []
items = ['Shoes', 'Caps', 'T-Shirts', 'Jeans', 'Socks']

while True:

    print("Following items available: ")
    for item in items:
        print(item)

    inp = int(input("Enter item number (1 - 5) to add to cart (Type '0' to exit): "))

    if inp == 0:
        break

    if inp in [1, 2, 3, 4, 5]:
        cart.append(items[inp - 1])
        print(f"{items[inp - 1]} added to cart!")
    else:
        print("Invalid input! Try again!")

print("Items in Cart: ")
for item in cart:
    print(item)

print("Goodbye!")


Following items available: 
Shoes
Caps
T-Shirts
Jeans
Socks
Shoes added to cart!
Following items available: 
Shoes
Caps
T-Shirts
Jeans
Socks
Caps added to cart!
Following items available: 
Shoes
Caps
T-Shirts
Jeans
Socks
Items in Cart: 
Shoes
Caps
Goodbye!


## Task 5
* Create two NumPy arrays of the same shape and perform element-wise addition on them.
* Calculate the element-wise product of two NumPy arrays.

In [57]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

print(np.add(arr1, arr2))
print(np.multiply(arr1, arr2))

[ 6 14 24 36 50]


## Task 6
* Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

* Concatenate two NumPy arrays horizontally and vertically.

In [63]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr2D = arr.reshape((3, 4))

print(arr2D)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Task 7
* Reverse A List In Python Using Slicing


In [65]:
lst = [1, 2, 3, 4, 5]
print(lst[::-1])

[5, 4, 3, 2, 1]


# TASK 8
You need to download the GitHub Desktop software, push your lab task to your GitHub account, and share the link on GCR as a submission.